about_page/urls.py
from django.urls import path
from .views import *

app_name = "about_page"
urlpatterns = [
    path('', about_page, name='about_page'),
    path('api/', about_json, name='about_json'),
]

pojok_belakang/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tugas1_crowdFunding.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('prog_detail/', include('program_detail.urls', namespace='program_detail')),
    path('programs/', include('program_donasi.urls', namespace='program_donasi')),
    path('about/', include('about_page.urls', namespace='about_page')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('profile/', include('profile_page.urls', namespace='profile_page')),
]

about_page/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.
class Comments(models.Model):
    name = models.CharField(max_length=1000)
    comment = models.TextField(max_length=99999)
    datetime = models.DateTimeField(default=now)

    def as_dict(self):
        return {
            'name' : self.name,
            'comment' : self.comment,
            'datetime' : self.datetime,
        }

about_page/forms.py
from .models import *
from django import forms
from django.forms import ModelForm

class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ["name", "comment"]

        widgets = {
            "name" : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'What name do you want to be displayed?'}),
            "comment" : forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Give us a nice testimony!'})
        }

about_page/views.py
from django.shortcuts import render, redirect, reverse
from .models import *
from .forms import *
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers

# Create your views here.

def about_page(request):
    form = CommentForm()
    # if (request.user.is_authenticated):
    if (request.method == "POST"):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, 'about.html', context={'form' : form})

def about_json(request):
    comments = [ obj.as_dict() for obj in Comments.objects.all().order_by('datetime') ]
    data = {"comments" : comments}
    return JsonResponse(data, safe=False)

about_page/templates/about.html
{% extends 'tugas1_crowdFunding/base.html' %}
{% load static %}
{% block script %}
<script>
var commentbox = [];
var lastLoad = 0;
function getComments(bool) {
    if (!bool) {
        $.get("/about/api/", function(data){
            console.log("MASUK AJAX")
            var komentar = data.comments;
            for (lastLoad; lastLoad < komentar.length; lastLoad++) {
                console.log(lastLoad);
                commentbox.push("<blockquote class='blockquote'><p>" + komentar[lastLoad].comment + "</p><footer class='blockquote-footer'>" + komentar[lastLoad].name + "</footer></blockquote><hr>")
            }
            $(".comment").append($(commentbox.join('')));
        });
    } else {
        $.get("/about/api/", function(data) {
            var komentar = data.comments;
            $(".comment").append("<blockquote class='blockquote'><p>" + komentar[komentar.length-1].comment + "</p><footer class='blockquote-footer'>" + komentar[komentar.length-1].name + "</footer></blockquote><hr>")
        })
    }
    
}
$(function() {
    var csrftoken = Cookies.get('csrftoken');
    getComments(false)

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }


    $("#comment-form").on("submit", function(event){
        event.preventDefault()
        console.log("Masuk Button");

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });


        $.post("/about/",{
            "name" : $("#id_name").val(),
            "comment" : $("#id_comment").val(),
        } ,function(data) {
            setTimeout(function() {
                getComments(true);
            }, 1000);
        })
    });
});


</script>
{% endblock script %}
{% block content %}
<div class="row">
    <div class="col-sm-6">
        <div class="sticky-top" style="padding-top:76px;">
            <h1>
                <strong>About PojokBelakang</strong>
            </h1>
            <hr>
            <p>
                Kita adalah orang-orang yang peduli dan empati terhadap masyarakat yang terkena musibah.
                Kami ingin membantu orang-orang tersebut untuk memenuhi kebutuhan mereka.
                Makanan. Minuman. Tempat tinggal. Uang. Semua bentuk akan mereka terima.
            </p>
            <p>
                Kami hanya ingin memenuhi tugas kami sebagai mahkluk hidup.
                Membantu, dan menjaga semua yang terkena musibah, ataupun keburukan.
            </p>
        </div>
    </div>
    <div class="col-sm-6">
        <h2>
            Apa kata mereka....
        </h2>
        <hr>
        <div class="comment">
            
        </div>
        {% if user.is_authenticated %}
        <form id="comment-form" action="" method="post">
            {% csrf_token %}
            {{ form.name }}
            {{ form.comment }}
            <input id="submitbutton" class="btn btn-primary" type="submit" value="Submit">
        </form>
        {% else %}
        <p>Login to give us testimonies...</p>
        {% endif %}
    </div>
</div>
{% endblock content %}
{% block footer %}
{% include 'tugas1_crowdFunding/footer.html' %}
{% endblock footer %}