about_page/urls.py
from django.urls import path
from .views import *

app_name = "about_page"
urlpatterns = [
    path('', about_page, name='about_page'),
    path('api/', about_json, name='about_json'),
]

pojok_belakang/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tugas1_crowdFunding.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('prog_detail/', include('program_detail.urls', namespace='program_detail')),
    path('programs/', include('program_donasi.urls', namespace='program_donasi')),
    path('about/', include('about_page.urls', namespace='about_page')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('profile/', include('profile_page.urls', namespace='profile_page')),
]

program_detail/urls.py
from django.urls import path
from program_detail import views

app_name = 'program_detail'
urlpatterns = [
    path('<int:pk>/', views.prog_detail, name='prog_detail'),
    path('<int:pk>/donate/', views.donate, name='donate'),
]

program_donasi/urls.py
from django.urls import path
from .views import *

app_name = 'program_donasi'
urlpatterns = [
    path('', programs, name='programs'),
]

tugas1_crowdFunding/urls.py
from django.urls import path, include
from tugas1_crowdFunding.views import index, newsView

app_name = 'tugas1_crowdFunding'
urlpatterns = [
    path('', index, name='index'),
    path('news/<int:news_id>', newsView, name='news'),
]

tugas1_crowdFunding/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    judul = models.CharField(max_length=100)
    isi_berita = models.TextField(max_length=1000)
    foto = models.TextField(max_length=9999999)

tugas1_crowdFunding/views.py
from django.shortcuts import render
from functools import reduce
import operator
from django.db.models import Q
from tugas1_crowdFunding.models import News
from program_detail.models import Program

def index(request):
	newslist = News.objects.all()
	context = {
		'news_list': newslist,
	}
	return render(request, 'tugas1_crowdFunding/landing_page.html', context)

def newsView(request, news_id):
	news = News.objects.get(pk=news_id)
	programs = find_related(news)

	context = {
		'title': news.judul,
		'news_content': news,
		'programs':programs
	}

	return render(request, 'tugas1_crowdFunding/news_page.html', context)

def find_related(news):
	name = news.judul.strip()
	query = reduce(operator.and_, (Q(title__contains = item) for item in name))
	return Program.objects.filter(query)

tugas1_crowdFunding/templates/tugas1_crowdFunding/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{{ title }} | Pojok Belakang</title>

		<!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"> -->
		 <!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

		<!-- Popper JS -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

		<link href="https://fonts.googleapis.com/css?family=Raleway|Slabo+13px" rel="stylesheet">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<!-- <link href="{% static 'css/style.css' %}" rel="stylesheet"> -->
		<link rel="stylesheet" href="{% static 'css/stylev2.css' %}">
		<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
		{% block stylesheet %}
		{% endblock stylesheet %}
	</head>
	<body>
		<header>
			<nav class="navbar navbar-expand-sm bg-primary navbar-dark fixed-top">
				<a href="{% url 'tugas1_crowdFunding:index' %}" class="navbar-brand">
					<img src="{% static 'images/logofixed.png' %}" style="max-height:50px;">
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="collapsibleNavbar">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'tugas1_crowdFunding:index' %}"><h4>Home</h4></a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'program_donasi:programs' %}"><h4>Programs</h4></a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'about_page:about_page' %}"><h4>About Us</h4></a>
						</li>
					</ul>
					{% if user.is_authenticated %}
					 <p class="display-4">Hello, {{ user.username }}</p>
					<a class="btn btn-info navbar-right navbar-btn" href="/profile/" id="register-button" style="margin-right: 10px"><h4>My Profile</h4></a>
			        {% else %}
					<a class="btn btn-info navbar-right navbar-btn" href="/login/" id="register-button"><h4>Register</h4></a>
					{% endif %}
				</div>
			</nav>
		</header>
		{% block background %}
		{% endblock background %}
		<div class="container-fluid">
			{% block content %}
			{% endblock content %}
		</div>
	</body>
	{% block footer %}
	{% endblock footer %}

	{% block script %}
	{% endblock script %}
</html>

tugas1_crowdFunding/templates/tugas1_crowdFunding/footer.html
{% block footer %}
<footer class="bg-primary container-fluid">
	<div class="row">
		<div class="col-md-6 mt-md-3 mt-3 ml-md-0">
			<strong>About the company</strong>
			<p>PojokBelakang membantu korban bencana alam dan terbelakang menemukan donatur yang bersedia membantu</p>
		</div>

		<div class="col-md-3 mt-md-3 mb-md-0 mb-3 mr-md-0">
			<ul class="list-unstyled">
				<li>
					<a class="ic">
						<i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3"></i>
					</a>
					<p>@pojokbelakang</p>
				</li>
				<br>
				<li>
					<a class="ic">
						<i class="fas fa-mobile fa-lg white-text mr-md-5 mr-3"></i>
					</a>
					<p>089634517819</p>
				</li>
			</ul>
		</div>

		<div class="col-md-3 mt-md-3 mb-md-0 mb-3 mr-md-0">
			<ul class="list-unstyled">
				<li>
					<a class="ic">
						<i class="far fa-envelope fa-lg white-text mr-md-5 mr-3"> </i>
					</a>
					<p>pojokbelakang@gmail.com</p>
				</li>
				<br>
				<li>
					<a class="ic">
						<i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3"> </i>
					</a>
					<p>@pojokbelakang</p>
				</li>
			</ul>
		</div>
	</div>
</footer>
{% endblock footer %}

tugas1_crowdFunding/templates/tugas1_crowdFunding/landing_page.html
{% extends 'tugas1_crowdFunding/base.html' %}
{% block background %}
<img src="https://nextrends.swissnexsanfrancisco.org/wp-content/uploads/2012/07/CrowdfundingPhoto-1728x800_c.jpg" class="img-fluid">
{% endblock background %}

{% block content %}
            <h1 class="text-center jumbotron">News</h1>
            {% if news_list %}
                {% for news in news_list %}
                {% if forloop.counter|divisibleby:3 or forloop.first %}
                <div class="row justify-content-around">
                {% endif %}
                <div class="card text-center" style="width:300px;">
                    <img class="card-img-top" src="{{ news.foto }}" alt="{{ news.judul }}">
                    <div class="card-body">
                        <h4 class="card-title">{{ news.judul }}</h4>
                        <p class="card-text">{{ news.isi_berita|truncatechars:50 }}</p>
                        <a href="/news/{{ news.id }}" class="btn btn-primary">Baca Berita</a>
                    </div>
                </div>
                {% if forloop.last %}
                </div>
                {% elif forloop.counter|divisibleby:3 %}
                </div>
                {% endif %}
                {% endfor %}
            {% endif %}
{% endblock content %}

{% block footer %}
{% include 'tugas1_crowdFunding/footer.html' %}
{% endblock footer %}

tugas1_crowdFunding/templates/tugas1_crowdFunding/news_page.html
{% extends 'tugas1_crowdFunding/base.html' %}
{% block content %}
    <div class="">
      <div class="row">
        <div class="col-sm-12 text-center">
            <h1>{{ news_content.judul }}</h1>
            <hr>
            <img class="img-fluid img-thumbnail" src="{{ news_content.foto }}" alt="{{ news_content.judul }}">
            <p>{{ news_content.isi_berita|linebreaks }}</p>
        </div>
      </div>
      <div class="row">
          {% for program in programs %}
          <div class="col-sm-4" style="margin-top:20px;">
            <div class="card bg-primary" style="width:350px;">
              <img src={{ program.image_url }} class="img-responsive card-img-top" style="width:100%;height:200px;">
              <div class="card-body">
                <h4 class="card-title">{{ program.title }}</h4>
                <a href="{% url 'program_detail:prog_detail' program.pk %}" class="btn btn-primary">See Details</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
    </div>
{% endblock content %}
{% block footer %}
{% include 'tugas1_crowdFunding/footer.html' %}
{% endblock footer %}