about_page/urls.py
from django.urls import path
from .views import *

app_name = "about_page"
urlpatterns = [
    path('', about_page, name='about_page'),
    path('api/', about_json, name='about_json'),
]

pojok_belakang/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tugas1_crowdFunding.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('prog_detail/', include('program_detail.urls', namespace='program_detail')),
    path('programs/', include('program_donasi.urls', namespace='program_donasi')),
    path('about/', include('about_page.urls', namespace='about_page')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('profile/', include('profile_page.urls', namespace='profile_page')),
]

program_detail/urls.py
from django.urls import path
from program_detail import views

app_name = 'program_detail'
urlpatterns = [
    path('<int:pk>/', views.prog_detail, name='prog_detail'),
    path('<int:pk>/donate/', views.donate, name='donate'),
]

program_detail/models.py
from django.db import models
from django.utils.timezone import now

class Program(models.Model):
	title = models.CharField(max_length=100)
	image_url = models.TextField()
	desc = models.TextField()
	datetime = models.DateTimeField(default=now)

class Donatur(models.Model):
	program = models.ForeignKey(Program, on_delete=models.CASCADE)
	nama = models.CharField(max_length=50)
	email = models.EmailField()
	jumlah = models.BigIntegerField()
	anon = models.BooleanField(default=False)

program_detail/forms.py
from django import forms
from .models import Donatur
from django.forms import ModelForm

class DonateForm(ModelForm):
	class Meta:
		model= Donatur
		fields = ['jumlah', 'anon']

		widgets = {
			'jumlah' : forms.NumberInput(attrs={'class' : 'form-control',
                                        'type' : 'number',
                                        'placeholder' : 'how much u wan to donate',
										'id': 'form_jumlah'}),
			'anon' : forms.CheckboxInput(attrs={'class': 'checkbox',
										'type' : 'checkbox',
										'id': 'form_anon'})
        }

program_detail/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import JsonResponse
from program_detail.models import *
from program_detail.forms import *

def prog_detail(request, pk):
	prog = Program.objects.get(pk=pk)
	form = DonateForm()
	donatur = Donatur.objects.all()

	content = {'title' : prog.title,
				'form' : form,
				'prog' : prog,
				'donatur' : donatur}

	return render(request, 'program_detail/prog_detail.html', content)

def donate(request, pk):
	auth_status = request.user.is_authenticated
	if auth_status:
		if request.method == "POST":
			jumlah = request.POST.get('jumlah', None)
			anon = request.POST.get('anon', None)
			anonim = False
			if anon == "true":
				anonim = True
			program = Program.objects.get(pk=pk)
			nama = request.user.first_name
			email =request.user.email
			Donatur.objects.create(nama=nama, program=program, email=email, jumlah=jumlah, anon=anonim)

	context = {
		'authenticated': auth_status
	}
	return JsonResponse(context)

program_detail/templates/program_detail/prog_detail.html
{% extends 'tugas1_crowdFunding/base.html' %}

{% block script %}
	<script>
		$("#donate_button").click( function() {
			if (document.getElementById("form_jumlah").value !== "") {
				$.ajax({
					type: "POST",
					url: '{% url 'program_detail:donate' prog.pk %}',
					data: {
						'jumlah': document.getElementById("form_jumlah").value,
						'anon': $("#form_anon").is(":checked"),
						'csrfmiddlewaretoken': '{{csrf_token}}',
					},
					dataType: 'json',
					success: function (data) {
						if (!data.authenticated) {
							alert('Anda belum login!');
						} else {
							$("#form_jumlah").val("");
							alert('Berhasil melakukan donasi');
						}
					}
				});
			} else {
				alert("jumlah yang anda masukkan salah")
			}
		});
	</script>
{% endblock %}

{% block content %}
<div class="">
	<div class="row">
		<div class="col-sm-12 text-center">
			<h1>{{ prog.title }}</h1>
			<hr>
			<img src="{{ prog.image_url }}" class="img-fluid img-thumbnail">
			<br>
			<br>
			<h4>{{ prog.desc|linebreaks }}</h4>
		</div>
	</div>
</div>

	<div class="col-sm-4">
		<div class="border">
			<form method="POST" class="form-group">
				{% csrf_token %}
				{{ form.jumlah }}
				{{ form.anon }} Donate as anonim
				<br>
				<br>
				<div class="mx-auto">
					<button class="btn btn-primary" id="donate_button" type="button"><h3>Donate</h3></button>
				</div>
			</form>
		</div>
		<br>
		<br>
		<div class="border">
			{% for donat in donatur %}
				{% if prog == donat.program %}
					{% if donat.anon is False %}
						<h4>{{ donat.nama }}</h4>
					{% else %}
						<h4>Donat Anonim</h4>
					{% endif %}
				{% endif %}
			{% endfor %}
		</div>
	</div>
</div>
{% endblock content %}

{% block footer %}
{% include 'tugas1_crowdFunding/footer.html' %}
{% endblock footer %}